# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:

    # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://172.18.32.1:9090
    # <bool> enable/disable basic auth
    basicAuth: false
    # <bool> enable/disable with credentials headers
    withCredentials: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
      httpMethod: "POST"
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.1"
    # <string> json object of data that will be encrypted.
    secureJsonFields: {}
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
