version: '3.8'

services:

  crdb:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach:v22.2.7
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - ../data:/cockroach/cockroach-data
    command: start --cluster-name=cockroach-cluster --insecure --join=crdb