version: '3.8'

services:

  crdb-1:
    container_name: crdb-1
    hostname: crdb-1
    image: cockroachdb/cockroach:${CRDB_VERSION}
    volumes:
      - ../data01:/cockroach/cockroach-data
    command: start --cluster-name=cockroach-cluster --insecure --join=crdb-1,crdb-2,crdb-3
    networks:
      prometheus:
        aliases:
          - node-1

  crdb-2:
    container_name: crdb-2
    hostname: crdb-2
    image: cockroachdb/cockroach:${CRDB_VERSION}
    volumes:
      - ../data02:/cockroach/cockroach-data
    command: start --cluster-name=cockroach-cluster --insecure --join=crdb-1,crdb-2,crdb-3
    deploy:
      resources:
        limits:
          memory: 4gb
          cpus: '0.5'
    networks:
      prometheus:
        aliases:
          - node-2

  crdb-3:
    container_name: crdb-3
    hostname: crdb-3
    image: cockroachdb/cockroach:${CRDB_VERSION}
    volumes:
      - ../data03:/cockroach/cockroach-data
    command: start --cluster-name=cockroach-cluster --insecure --join=crdb-1,crdb-2,crdb-3
    deploy:
      resources:
        limits:
          memory: 3gb
          cpus: '0.5'
    networks:
      prometheus:
        aliases:
          - node-3

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:${NGINX_VERSION}
    volumes:
      # to load configuration
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "26257:26257"
    depends_on:
      - crdb-1
      - crdb-2
      - crdb-3
    networks:
      prometheus:
        aliases:
          - nginx

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # to provision configuration
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # to persist scraped data
      - ../prometheus-data:/prometheus/data
    ports:
      - 9090:9090
    networks:
      prometheus:
        aliases:
          - prometheus

  grafana:
    container_name: grafana 
    hostname: grafana
    image: grafana/grafana-oss:${GRAFANA_VERSION}
    volumes:
      # to provision datasources and dashboards
      - ../grafana/provisioning:/etc/grafana/provisioning/
      - ../grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      prometheus:
        aliases:
          - grafana

networks:
  prometheus:
    name: prometheus
    driver: bridge