{
 "title": "CockroachDB Custom",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"cockroachdb\"}"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "5s,10s,30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open SQL Sessions",
   "type": "graph",
   "description": "The total number of open SQL Sessions.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sql_conns{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "graph",
   "description": "A moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "SELECT per instance",
   "type": "timeseries",
   "description": "A moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sql_select_count{job=\"cockroachdb\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Live Node Count",
   "type": "graph",
   "description": "The number of live nodes in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "nodes" }
   ],
   "targets": [
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Replicas per Node",
   "type": "graph",
   "description": "The number of range replicas stored on this node. Ranges are subsets of your data, which are replicated to ensure survivability.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "replicas{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "graph",
   "description": "A ten-second moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second across all nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Read B/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(sys_host_disk_read_bytes{job=\"cockroachdb\",instance=~\"$node\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "description": "Usage of disk space\n\n**Capacity**: Maximum store size across all nodes. This value may be explicitly set per node using [--store](https://www.cockroachlabs.com/docs/v21.1/cockroach-start.html#store). If a store size has not been set, this metric displays the actual disk capacity.\n\n**Available**: Free disk space available to CockroachDB data across all nodes.\n\n**Used**: Disk space in use by CockroachDB data across all nodes. This excludes the Cockroach binary, operating system, and other system files.\n\n[How are these metrics calculated?](https://www.cockroachlabs.com/docs/v21.1/ui-storage-dashboard.html#capacity-metrics)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes", "label": "capacity" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity_available{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}) by (cluster))",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(sum(capacity_used{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}) by (cluster))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory in use across all nodes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "bytes", "label": "memory usage" }
   ],
   "targets": [
    {
     "expr": "sys_rss{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Panel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      { "expr": "liveness_livenodes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "New Panel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "sys_rss", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "sql_select_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "rate(sql_select_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}